import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className='bg-blue-200 h-24'>
          <h1>header bar</h1>
        </header>
        {children}
        <footer className='bg-gray-200 h-24'>
          <h1>footer bar</h1>
        </footer>
      </body>
    </html>
  )
}