export const metadata = {
    title: 'Product',
    description: 'Generated by next app',
  }

export default function product(){
    return(
        <div className="product-id">
            <h1 className="product-id">products</h1>
        </div>
    );
}