export const metadata = {
    title: 'Blog',
    description: 'Generated by next app',
  }

export default function second(){
    return(
        <div>
            <h1>second page</h1>
        </div>
    );
}