export const metadata = {
    title: 'About',
    description: 'Generated by next app',
  }

export default function About() {
    return (
        <>
            <section className="container mx-auto py-16 px-6 text-center">
                <h2 className="text-4xl font-bold text-black mb-10">About Us</h2>
                <div className="flex flex-col md:flex-row items-center justify-center">

                    <div className="md:w-1/2 md:pl-10">
                        <p className="text-gray-800 text-lg mb-6">
                            At Cafe Delight, we believe in offering a perfect blend of atmosphere and taste. Established in 2010, our mission has been to provide a cozy and welcoming space for coffee lovers and food enthusiasts alike. Whether you're here for a quick coffee or a long brunch with friends, we're here to make your experience unforgettable.
                        </p>
                        <p className="text-gray-800 text-lg mb-6">
                            We pride ourselves on using the finest ingredients in our menu, sourcing locally wherever possible. Our baristas are trained to craft the perfect cup, and our chefs are passionate about creating dishes that surprise and delight.
                        </p>
                        <p className="text-gray-800 text-lg mb-6">
                            Our cafe features a warm and inviting atmosphere, designed to make you feel right at home. From comfortable seating to free Wi-Fi, we provide the perfect environment for work, relaxation, or socializing.
                        </p>
                        <p className="text-gray-800 text-lg mb-6">
                            We also host regular events, including coffee tastings, live music, and art exhibitions, fostering a sense of community and creativity among our patrons. 
                        </p>
                        <p className="text-gray-800 text-lg">
                            Come visit us today and experience the warmth of Cafe Delight. We’re more than just a café – we’re a community hub where stories are shared over delicious food and drinks.
                        </p>
                    </div>
                </div>
            </section>
        </>
    );
}
